Repository FAP-Cloud-Service/FAP-Frontend, pull requests merged in 2021-04, with the labels that each got.

#11 basic login mask
  FriendsAndPlaces/src/app/app.component.html
  FriendsAndPlaces/src/app/app.component.spec.ts
  FriendsAndPlaces/src/app/app.module.ts
  FriendsAndPlaces/src/app/login/login.component.html
  FriendsAndPlaces/src/app/login/login.component.scss
  FriendsAndPlaces/src/app/login/login.component.ts
  FriendsAndPlaces/src/app/services/login.service.ts
  FriendsAndPlaces/src/index.html
Labels: good first issue

#13 Start page
  FriendsAndPlaces/src/app/app.component.html
  FriendsAndPlaces/src/app/app.component.scss
  FriendsAndPlaces/src/app/app.component.ts
  FriendsAndPlaces/src/app/app.module.ts
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.html
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.scss
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.spec.ts
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.ts
  FriendsAndPlaces/src/app/start-page/start-page.component.html
  FriendsAndPlaces/src/app/start-page/start-page.component.scss
  FriendsAndPlaces/src/app/start-page/start-page.component.spec.ts
  FriendsAndPlaces/src/app/start-page/start-page.component.ts
  FriendsAndPlaces/tsconfig.json
Labels: enhancement

#16 Feature/docker deployment
  .github/workflows/deploy-docker.yml
  Dockerfile
  FriendsAndPlaces/package.json
  FriendsAndPlaces/src/app/abort-dialog/abort-dialog.component.html
  FriendsAndPlaces/src/app/abort-dialog/abort-dialog.component.scss
  FriendsAndPlaces/src/app/abort-dialog/abort-dialog.component.ts
  FriendsAndPlaces/src/app/app.component.ts
  FriendsAndPlaces/src/app/app.module.ts
  FriendsAndPlaces/src/app/login/login.component.html
  FriendsAndPlaces/src/app/login/login.component.scss
  FriendsAndPlaces/src/app/login/login.component.ts
  FriendsAndPlaces/src/app/register/register.component.html
  FriendsAndPlaces/src/app/register/register.component.scss
  FriendsAndPlaces/src/app/register/register.component.ts
  FriendsAndPlaces/src/app/services/country.service.ts
  FriendsAndPlaces/src/app/services/login.service.ts
  FriendsAndPlaces/src/app/services/zipcode.service.ts
  FriendsAndPlaces/src/app/start-page/start-page.component.scss
Labels: DevOps

#20 Test der neuen Release-Pipeline
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-docker.yml
  .gitignore
  Dockerfile
  FriendsAndPlaces/.browserslistrc
  FriendsAndPlaces/.editorconfig
  FriendsAndPlaces/README.md
  FriendsAndPlaces/angular.json
  FriendsAndPlaces/e2e/protractor.conf.js
  FriendsAndPlaces/e2e/src/app.e2e-spec.ts
  FriendsAndPlaces/e2e/src/app.po.ts
  FriendsAndPlaces/e2e/tsconfig.json
  FriendsAndPlaces/karma.conf.js
  FriendsAndPlaces/package-lock.json
  FriendsAndPlaces/package.json
  FriendsAndPlaces/src/app/abort-dialog/abort-dialog.component.html
  FriendsAndPlaces/src/app/abort-dialog/abort-dialog.component.scss
  FriendsAndPlaces/src/app/abort-dialog/abort-dialog.component.ts
  FriendsAndPlaces/src/app/app.component.html
  FriendsAndPlaces/src/app/app.component.scss
  FriendsAndPlaces/src/app/app.component.ts
  FriendsAndPlaces/src/app/app.module.ts
  FriendsAndPlaces/src/app/login/login.component.html
  FriendsAndPlaces/src/app/login/login.component.scss
  FriendsAndPlaces/src/app/login/login.component.ts
  FriendsAndPlaces/src/app/modules/material/material.module.ts
  FriendsAndPlaces/src/app/register/register.component.html
  FriendsAndPlaces/src/app/register/register.component.scss
  FriendsAndPlaces/src/app/register/register.component.ts
  FriendsAndPlaces/src/app/services/country.service.ts
  FriendsAndPlaces/src/app/services/login.service.ts
  FriendsAndPlaces/src/app/services/zipcode.service.ts
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.html
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.scss
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.spec.ts
  FriendsAndPlaces/src/app/sidenav-content/sidenav-content.component.ts
  FriendsAndPlaces/src/app/start-page/start-page.component.html
  FriendsAndPlaces/src/app/start-page/start-page.component.scss
  FriendsAndPlaces/src/app/start-page/start-page.component.spec.ts
  FriendsAndPlaces/src/app/start-page/start-page.component.ts
  FriendsAndPlaces/src/assets/.gitkeep
  FriendsAndPlaces/src/environments/environment.prod.ts
  FriendsAndPlaces/src/environments/environment.ts
  FriendsAndPlaces/src/favicon.ico
  FriendsAndPlaces/src/index.html
  FriendsAndPlaces/src/main.ts
  FriendsAndPlaces/src/polyfills.ts
  FriendsAndPlaces/src/styles.scss
  FriendsAndPlaces/src/test.ts
  FriendsAndPlaces/tsconfig.app.json
  FriendsAndPlaces/tsconfig.json
  FriendsAndPlaces/tsconfig.spec.json
  FriendsAndPlaces/tslint.json
  README.md
  SECURITY.md
Labels: DevOps, enhancement, help wanted
